package fr.nadouani.gab

class Project {
	static mapping = {
		table "gab_project"
		
		tables cascade:'all-delete-orphan'
		
		ddl type: "text"
	}

	/**
	 * Project properties
	 */
	String name
	Boolean imported = true
	
	/**
	 * Datasource properties
	 */
	String dbName
	String dbType
	String dbHost
	String dbUsername
	String dbPassword
	String dbPort

	/**
	 * The original ddl generated by ddlUtils
	 */
	String ddl
	
	User owner
	
	static belongsTo = [owner: User]
	static hasMany = [tables:Table]
	
    static constraints = {
		name (nullable:false, blank:false)
		dbName (nullable:false, blank:false)
		dbType (nullable:false, blank:false, inList:['MYSQL', 'ORACLE', 'MSSQL'])
		dbHost (nullable:false, blank:false)
		dbPort(nullable:false, blank:false)
		dbUsername (nullable:false, blank:false)
		dbPassword (nullable:false, blank:true)
		imported(nullable:false)
    }
	
	String toString(){
		"$name"
	}
}
